#!/usr/bin/env node
/**
 * build-pages.mjs
 *
 * Bakes the canonical site header and footer (from js/header.js and js/footer.js)
 * directly into every root-level *.html page. Crawlers and AI/LLM bots that don't
 * execute JavaScript can then see the full nav, internal links, and footer content.
 *
 * The runtime JS files remain the single source of truth. After editing the
 * `headerHTML` or `footerHTML` template literal inside them, re-run this script:
 *
 *     node tools/build-pages.mjs
 *
 * The script is idempotent — it replaces content between
 *     <!-- HEADER:START --> ... <!-- HEADER:END -->
 * and the equivalent footer markers — so it's safe to run any number of times.
 *
 * Pages are matched by the original placeholder `<div id="site-header"></div>`
 * on first run; on subsequent runs the markers themselves are matched.
 */

import { readFile, writeFile, readdir } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');

// ─── Extract canonical header/footer HTML from the JS source files ───────────

function extractTemplate(jsSource, varName) {
  // Match `const <varName> = ` followed by a backtick template literal.
  const re = new RegExp(`const\\s+${varName}\\s*=\\s*\`([\\s\\S]*?)\`\\s*;`);
  const m = jsSource.match(re);
  if (!m) {
    throw new Error(`Could not find template literal "${varName}" in JS source`);
  }
  return m[1].trim();
}

const headerJs = await readFile(join(ROOT, 'js', 'header.js'), 'utf8');
const footerJs = await readFile(join(ROOT, 'js', 'footer.js'), 'utf8');

const headerHTML = extractTemplate(headerJs, 'headerHTML');
const footerHTML = extractTemplate(footerJs, 'footerHTML');

// ─── Build the inlined blocks (with markers for idempotent re-runs) ──────────

const headerBlock = [
  '<!-- HEADER:START — generated by tools/build-pages.mjs; edit js/header.js then re-run -->',
  headerHTML,
  '<!-- HEADER:END -->',
].join('\n');

const footerBlock = [
  '<!-- FOOTER:START — generated by tools/build-pages.mjs; edit js/footer.js then re-run -->',
  footerHTML,
  '<!-- FOOTER:END -->',
].join('\n');

// ─── Replacement logic ───────────────────────────────────────────────────────

const HEADER_MARKER_RE = /<!--\s*HEADER:START[\s\S]*?<!--\s*HEADER:END\s*-->/;
const FOOTER_MARKER_RE = /<!--\s*FOOTER:START[\s\S]*?<!--\s*FOOTER:END\s*-->/;

// First-run patterns: original placeholder + optional preceding HTML comment.
const HEADER_PLACEHOLDER_RE =
  /(?:<!--\s*HEADER[^>]*?-->\s*)?<div\s+id=["']site-header["']\s*>\s*<\/div>/i;
const FOOTER_PLACEHOLDER_RE =
  /(?:<!--\s*FOOTER[^>]*?-->\s*)?<div\s+id=["']site-footer["']\s*>\s*<\/div>/i;

function injectBlock(html, markerRe, placeholderRe, block) {
  if (markerRe.test(html)) return html.replace(markerRe, block);
  if (placeholderRe.test(html)) return html.replace(placeholderRe, block);
  return null; // No injection point found
}

// ─── Process every root-level .html file (skip backups) ──────────────────────

const SKIP = new Set(['index_1.html', 'index-orbital.html']);

const entries = await readdir(ROOT, { withFileTypes: true });
const htmlFiles = entries
  .filter((e) => e.isFile() && e.name.endsWith('.html') && !SKIP.has(e.name))
  .map((e) => e.name)
  .sort();

let updated = 0;
let skipped = 0;
const noInjectionPoint = [];

for (const file of htmlFiles) {
  const path = join(ROOT, file);
  const original = await readFile(path, 'utf8');

  let next = original;

  const afterHeader = injectBlock(next, HEADER_MARKER_RE, HEADER_PLACEHOLDER_RE, headerBlock);
  if (afterHeader === null) {
    noInjectionPoint.push(`${file} (header)`);
  } else {
    next = afterHeader;
  }

  const afterFooter = injectBlock(next, FOOTER_MARKER_RE, FOOTER_PLACEHOLDER_RE, footerBlock);
  if (afterFooter === null) {
    noInjectionPoint.push(`${file} (footer)`);
  } else {
    next = afterFooter;
  }

  if (next === original) {
    skipped++;
  } else {
    await writeFile(path, next, 'utf8');
    updated++;
  }
}

console.log(`build-pages: updated ${updated}, unchanged ${skipped}, total ${htmlFiles.length}`);
if (noInjectionPoint.length) {
  console.log(`No injection point found in:`);
  for (const f of noInjectionPoint) console.log(`  - ${f}`);
}
